# Generated by Django 6.0.1 on 2026-01-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singlepiece",
            options={
                "ordering": ["sku"],
                "verbose_name": "Produto Acrílico",
                "verbose_name_plural": "Produtos Acrílicos",
            },
        ),
        migrations.RemoveField(
            model_name="singlepiece",
            name="price",
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="acrylic_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRISTAL", "Cristal"),
                    ("BRANCO", "Branco"),
                    ("PRETO", "Preto"),
                    ("ROSA", "Rosa"),
                    ("ROSA_BEBE", "Rosa Bebê"),
                    ("AZUL", "Azul"),
                    ("AZUL_BEBE", "Azul Bebê"),
                    ("ESPELHADO", "Espelhado"),
                    ("ESPELHADO_TRANSPARENTE", "Espelhado Transparente"),
                    ("COLORIDO", "Colorido"),
                ],
                max_length=30,
                null=True,
                verbose_name="Cor do acrílico",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço base",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="color_observation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Observação de cor"
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="curvature_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Curvatura (cm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="depth_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Profundidade (cm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="diameter_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Diâmetro (cm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="has_electrical_component",
            field=models.BooleanField(
                default=False, verbose_name="Possui componente elétrico?"
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="has_led",
            field=models.BooleanField(default=False, verbose_name="Possui LED?"),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Altura (cm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="is_sellable",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, aparece no catálogo e exige preço",
                verbose_name="É vendável?",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="led_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Selecione..."), ("QUENTE", "Quente"), ("FRIO", "Frio")],
                max_length=10,
                verbose_name="Tipo de LED",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Comprimento (cm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="thickness_mm",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "2 mm"),
                    (3, "3 mm"),
                    (4, "4 mm"),
                    (6, "6 mm"),
                    (8, "8 mm"),
                    (10, "10 mm"),
                    (12, "12 mm"),
                ],
                default=3,
                verbose_name="Espessura (mm)",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="voltage",
            field=models.CharField(
                blank=True,
                choices=[("", "Selecione..."), ("127", "127V"), ("BIVOLT", "Bivolt")],
                max_length=10,
                verbose_name="Tensão",
            ),
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Largura (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="singlepiece",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogo.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="singlepiece",
            name="sku",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="SKU (código interno)"
            ),
        ),
    ]
