# Generated by Django 6.0.1 on 2026-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogo",
            "0002_alter_singlepiece_options_remove_singlepiece_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="singlepiece",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/single_pieces/",
                verbose_name="Foto do produto",
            ),
        ),
    ]
