# Generated by Django 6.0.1 on 2026-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_singlepiece_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
    ]
