# Generated by Django 6.0.1 on 2026-02-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_compositions",
                        to="catalogo.singlepiece",
                        verbose_name="Produto componente",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="catalogo.singlepiece",
                        verbose_name="Produto composto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de Produto",
                "verbose_name_plural": "Componentes de Produto",
                "ordering": ["id"],
                "unique_together": {("parent", "component")},
            },
        ),
    ]
