# Generated by Django 6.0.1 on 2026-02-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_productcomponent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Kit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="KitComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "composed_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_kits",
                        to="catalogo.productcomponent",
                        verbose_name="Produto composto",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="catalogo.kit",
                        verbose_name="Kit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in_kits",
                        to="catalogo.singlepiece",
                        verbose_name="Produto simples",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de Kit",
                "verbose_name_plural": "Componentes de Kit",
                "ordering": ["id"],
                "unique_together": {("kit", "composed_product"), ("kit", "product")},
            },
        ),
    ]
