# Generated by Django 6.0.1 on 2026-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0006_kit_kitcomponent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singlepiece",
            options={},
        ),
        migrations.AddField(
            model_name="singlepiece",
            name="is_kit",
            field=models.BooleanField(
                default=False,
                help_text="Identifica se este produto é um kit",
                verbose_name="É kit?",
            ),
        ),
    ]
