# Generated by Django 6.0.1 on 2026-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_alter_singlepiece_options_singlepiece_is_kit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlepiece",
            name="voltage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione..."),
                    ("127", "127V"),
                    ("220", "220V"),
                    ("BIVOLT", "Bivolt"),
                ],
                max_length=10,
                verbose_name="Tensão",
            ),
        ),
    ]
