# Generated by Django 6.0.1 on 2026-03-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0008_alter_singlepiece_voltage"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço base",
            ),
        ),
        migrations.AlterField(
            model_name="kitcomponent",
            name="composed_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_kits_as_composed",
                to="catalogo.singlepiece",
                verbose_name="Produto composto",
            ),
        ),
    ]
