# Generated by Django 6.0.1 on 2026-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=30, unique=True, verbose_name="Chave"),
                ),
                (
                    "last_value",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Último valor"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Prefixo"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sequência",
                "verbose_name_plural": "Sequências",
                "ordering": ["key"],
            },
        ),
    ]
