# Generated by Django 6.0.1 on 2026-02-27 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atualização"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Validade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Em aberto"),
                            ("approved", "Aprovado"),
                            ("rejected", "Reprovado"),
                            ("expired", "Expirado"),
                            ("canceled", "Cancelado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Venda direta"),
                            ("exchange", "Troca"),
                            ("maintenance", "Manutenção"),
                            ("advertising", "Publicidade"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de venda",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Condição de pagamento"
                    ),
                ),
                (
                    "customer_order",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pedido do cliente"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contato"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transportadora"
                    ),
                ),
                (
                    "freight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Frete"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Observações internas"),
                ),
                (
                    "total_products",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total produtos",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total desconto",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total geral",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="clientes.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["number"], name="vendas_budg_number_3a9da0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="vendas_budg_status_bb28b7_idx"
                    ),
                ],
            },
        ),
    ]
