# Generated by Django 6.0.1 on 2026-03-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0008_alter_singlepiece_voltage"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor unitário"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vendas.budget",
                        verbose_name="Orçamento",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.singlepiece",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Orçamento",
                "verbose_name_plural": "Itens do Orçamento",
                "unique_together": {("budget", "product")},
            },
        ),
    ]
