# Generated by Django 6.0.1 on 2026-03-03 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_budgetitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Desconto geral (%)",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="freight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Frete",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Total geral",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Total desconto",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="total_products",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Total produtos",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Preenchido automaticamente com o preço base do produto.",
                max_digits=10,
                verbose_name="Valor unitário",
            ),
        ),
    ]
