# Generated by Django 6.0.1 on 2026-03-04 13:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0009_kit_base_price_alter_kitcomponent_composed_product"),
        ("clientes", "0001_initial"),
        ("vendas", "0003_budget_discount_alter_budget_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número do pedido",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atualização"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de entrega prevista"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Em aberto / Novo"),
                            ("approved", "Aprovado / Aguardando produção"),
                            ("in_production", "Em Produção"),
                            ("picking", "Em Separação / Faturando"),
                            ("invoiced", "Faturado / NF emitida"),
                            ("shipped", "Em Trânsito / Enviado"),
                            ("delivered", "Entregue"),
                            ("canceled", "Cancelado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status do pedido",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Venda direta"),
                            ("exchange", "Troca"),
                            ("maintenance", "Manutenção"),
                            ("advertising", "Publicidade"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de venda",
                    ),
                ),
                (
                    "customer_order",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pedido do cliente"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Condição de pagamento"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contato"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transportadora"
                    ),
                ),
                (
                    "freight",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Frete"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Observações internas"),
                ),
                (
                    "total_products",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total produtos",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total desconto",
                    ),
                ),
                (
                    "total_taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total impostos (IPI + ICMS)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total geral",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "budget",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_order_relation",
                        to="vendas.budget",
                        verbose_name="Orçamento de origem",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clientes.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor unitário"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Desconto por unidade (R$)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vendas.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogo.singlepiece",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["number"], name="vendas_orde_number_741c30_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="vendas_orde_status_09bd98_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
