# Generated by Django 6.0.1 on 2026-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_order_orderitem_order_vendas_orde_number_741c30_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_date",
        ),
    ]
