# Generated by Django 6.0.1 on 2026-03-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_remove_order_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="down_payment_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Entrada acordada (%)",
            ),
        ),
    ]
