# Generated by Django 6.0.1 on 2026-03-05 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0006_order_down_payment_percent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="budget",
            name="vendas_budg_number_3a9da0_idx",
        ),
        migrations.RemoveIndex(
            model_name="budget",
            name="vendas_budg_status_bb28b7_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="budget",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de entrega prevista"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True,
                help_text="Ex: contratada, retirada pelo cliente, por conta da empresa",
                max_length=50,
                verbose_name="Transportadora",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="down_payment_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentual mínimo para liberar produção (ex: 30 = 30%)",
                max_digits=5,
                verbose_name="Entrada acordada (%)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Em aberto / Novo"),
                    ("in_production", "Em Produção"),
                    ("picking", "Em Separação / Faturando"),
                    ("invoiced", "Faturado / NF emitida"),
                    ("shipped", "Em Trânsito / Enviado"),
                    ("delivered", "Entregue"),
                    ("canceled", "Cancelado"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status do pedido",
            ),
        ),
        migrations.RemoveField(
            model_name="budget",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="client",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="BudgetItem",
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
