# Generated by Django 6.0.1 on 2026-03-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0008_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("pix", "PIX"),
                    ("debit", "Cartão de Débito"),
                    ("credit", "Cartão de Crédito"),
                    ("boleto", "Boleto"),
                    ("cash", "Dinheiro"),
                    ("transfer", "Transferência"),
                ],
                default="pix",
                max_length=20,
                verbose_name="Forma de pagamento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.CharField(
                blank=True,
                help_text="Código PIX, NSU do cartão, número do boleto etc.",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Número de transação",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="vendas.order",
                verbose_name="Pedido",
            ),
        ),
    ]
