# Generated by Django 6.0.1 on 2026-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0009_payment_method_payment_notes_payment_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Transportadora"
            ),
        ),
    ]
