# Generated by Django 6.0.1 on 2026-03-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0009_kit_base_price_alter_kitcomponent_composed_product"),
        ("vendas", "0010_alter_order_carrier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
            },
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="kit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.kit",
                verbose_name="Kit",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Em aberto"),
                    ("in_production", "Em Produção"),
                    ("picking", "Em Separação / Faturando"),
                    ("invoiced", "Faturado / NF emitida"),
                    ("shipped", "Em Trânsito / Enviado"),
                    ("delivered", "Entregue"),
                    ("canceled", "Cancelado"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status do pedido",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalogo.singlepiece",
                verbose_name="Produto",
            ),
        ),
    ]
