# Generated by Django 6.0.1 on 2026-03-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0012_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="shipments/%Y/%m/",
                        verbose_name="Comprovante de envio",
                    ),
                ),
                (
                    "tracking",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Código de rastreio"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transportadora"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="vendas.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envio",
                "verbose_name_plural": "Envios",
            },
        ),
    ]
