# Generated by Django 6.0.1 on 2026-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0013_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Em aberto"),
                    ("in_production", "Em Produção"),
                    ("picking", "Em Separação"),
                    ("invoiced", "Faturado"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("canceled", "Cancelado"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status do pedido",
            ),
        ),
    ]
