# Generated by Django 6.0.1 on 2026-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0014_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="sale_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direct", "Venda direta"),
                    ("replacement", "Reposição"),
                    ("exchange", "Troca"),
                    ("maintenance", "Manutenção"),
                    ("advertising", "Publicidade"),
                ],
                max_length=20,
                verbose_name="Tipo de venda",
            ),
        ),
    ]
