# Generated by Django 6.0.1 on 2026-03-31 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0015_alter_order_sale_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Desconto total (R$)",
            ),
        ),
    ]
