# Generated by Django 6.0.1 on 2026-03-31 20:03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0016_alter_orderitem_discount"),
    ]

    operations = []
