# Generated by Django 6.0.1 on 2026-04-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0017_remove_discount_from_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discount",
        ),
    ]
