# Generated by Django 6.0.1 on 2026-02-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome / Razão Social"
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        max_length=18, unique=True, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Inscrição Estadual"
                    ),
                ),
                (
                    "municipal_registration",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Inscrição Municipal"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("complement", models.CharField(blank=True, max_length=255)),
                ("neighborhood", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                ("consent_source", models.CharField(blank=True, max_length=100)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_supplier", models.BooleanField(default=False)),
                ("is_carrier", models.BooleanField(default=False)),
                ("is_partner", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="clientes_cl_code_fe2fe5_idx"),
                    models.Index(
                        fields=["document"], name="clientes_cl_documen_b68796_idx"
                    ),
                    models.Index(fields=["name"], name="clientes_cl_name_3648d4_idx"),
                ],
            },
        ),
    ]
